/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import javax.swing.JOptionPane;
import simuladorcarro.Llanta;
import simuladorcarro.LlantaBarata;
import simuladorcarro.LlantaBonita;
import simuladorcarro.LlantaBuena;
import simuladorcarro.Motor;
import simuladorcarro.Motor1000Cc;
import simuladorcarro.Motor2000Cc;
import simuladorcarro.Motor3000Cc;
import simuladorcarro.Registro;
import simuladorcarro.Vehiculo;

/**
 *
 * @author juano
 */
public class VentanaCrearCarro extends javax.swing.JDialog {

    private Registro registro;
    /**
     * Creates new form VentanaCrearCarro
     */
    public VentanaCrearCarro(java.awt.Frame parent, boolean modal, Registro registro) {
        super(parent, modal);
        initComponents();
        this.registro = registro;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        txColor1 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        txColor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txMarca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txPlaca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbLlanta = new javax.swing.JComboBox<>();
        cbMotor = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btAceptar = new javax.swing.JButton();

        txColor1.setBackground(new java.awt.Color(204, 255, 255));

        jComboBox2.setBackground(new java.awt.Color(204, 255, 255));
        jComboBox2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Llanta buena", "Llantas bonita", "Llanta barata" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(29, 55, 82));

        txColor.setBackground(new java.awt.Color(80, 191, 195));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MARCA");

        txMarca.setBackground(new java.awt.Color(80, 191, 195));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("COLOR");

        txPlaca.setBackground(new java.awt.Color(80, 191, 195));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PLACA");

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LLANTA");

        cbLlanta.setBackground(new java.awt.Color(80, 191, 195));
        cbLlanta.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        cbLlanta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Llanta buena", "Llanta bonita", "Llanta barata" }));
        cbLlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLlantaActionPerformed(evt);
            }
        });

        cbMotor.setBackground(new java.awt.Color(80, 191, 195));
        cbMotor.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        cbMotor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1000 CC", "2000 CC", "3000 CC" }));
        cbMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMotorActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MOTOR");

        btAceptar.setBackground(new java.awt.Color(33, 77, 114));
        btAceptar.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btAceptar.setText("Aceptar");
        btAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txColor, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(94, 94, 94))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbLlanta, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAceptar))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbLlanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btAceptar)
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbLlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLlantaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLlantaActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void cbMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMotorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMotorActionPerformed

    private void btAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceptarActionPerformed
     String marca = this.txMarca.getText();
     String color = this.txColor.getText();
     String placa = this.txPlaca.getText();
     
     if (!txMarca.getText().isEmpty() && !txColor.getText().isEmpty() && !txPlaca.getText().isEmpty()) {
            Vehiculo vehiculoACrear;
            Llanta llantaTemp = elegirLlanta();
            Motor motorTemp = elegirMotor();
            
            vehiculoACrear = new Vehiculo(marca,color,placa,motorTemp,llantaTemp);
            

            boolean sePudo = this.registro.agregarVehiculo(vehiculoACrear);
            if (sePudo) {
                JOptionPane.showMessageDialog(this, "Vehiculo creado");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Vehiculo no creado");
        }
        this.dispose();
     
    }//GEN-LAST:event_btAceptarActionPerformed


    public Llanta elegirLlanta(){
        Llanta elegirLlanta;
        String tipoLlanta = String.valueOf(cbLlanta.getSelectedItem());
        if(tipoLlanta.equals("Llanta buena")){
            return elegirLlanta = new LlantaBuena();
        }  
        if(tipoLlanta.equals("Llanta bonita")){
            return elegirLlanta = new LlantaBonita();
        }
        if(tipoLlanta.equals("Llanta barata")){
            return elegirLlanta = new LlantaBarata();
        }
        return null;
    }
    public Motor elegirMotor(){
        Motor elegirMotor;
        String tipoMotor = String.valueOf(cbMotor.getSelectedItem());
        if(tipoMotor.equals("1000 CC")){
            return elegirMotor = new Motor1000Cc();
        }  
        if(tipoMotor.equals("2000 CC")){
            return elegirMotor = new Motor2000Cc();
        }
        if(tipoMotor.equals("3000 CC")){
            return elegirMotor = new Motor3000Cc();
        }
        return null;
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAceptar;
    private javax.swing.JComboBox<String> cbLlanta;
    private javax.swing.JComboBox<String> cbMotor;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField txColor;
    private javax.swing.JTextField txColor1;
    private javax.swing.JTextField txMarca;
    private javax.swing.JTextField txPlaca;
    // End of variables declaration//GEN-END:variables
}
